name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: DevOps WorkFlow
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.401
    - name: Build DotNet Devops Application
      run: dotnet build --configuration Release
    - name: Publish DotNet Devops application
      run: dotnet publish --configuration Release --output bin/Release/publish
      env:
        PublishFolder: bin/Release/publish
    - name: Create an executable .exe file
      run: |
        cd "$PublishFolder"
        dotnet publish -r win-x64 --self-contained false --output "$PublishFolder/win-x64"
